apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: avco2ass6-python 
  janus-idp.io/tekton: avco2ass6-python
  backstage.io/kubernetes-id: avco2ass6-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: avco2ass6-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml