apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: avco2ass6-python
  janus-idp.io/tekton: avco2ass6-python
  backstage.io/kubernetes-id: avco2ass6-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: avco2ass6-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
